### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by vladfaust** [amberframework/micrate#19]
Extracted from #13.

My workflow for migrations now involves PGAdmin SQL console to find a error because Micrate just silently doesn't apply a migration when something's wrong :sweat_smile: 

I suppose that a good solution is just to put SQL error message into the logger.

**Comment by vladfaust** [comment]
@faustinoaq I certainly did, this can be closed if you won’t display SQL errors 😉

**Comment by faustinoaq** [comment]
Well, I think SQL erros can be a good thing for amber, @amberframework/contributors WDYT?
