### ISSUE TITLE
Incremental numbers in migration names (001_name.sql)

### ISSUE THREAD

**Issue by vladfaust** [amberframework/micrate#20]
Timestamps VS Integers, well described [here](http://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-Two+separate+migrators). My proposal is to allow a developer to select whether to use timestamps or integers. Your thoughts?

**Comment by faustinoaq** [comment]
OMG, this was the "ghost" issue that was causing us headaches on Travis CI :sweat_smile: 

Please, see https://github.com/amberframework/micrate/issues/20
