### ISSUE TITLE
Protect against `IndexError`

### ISSUE THREAD

**Issue by marksiemers** [amberframework/micrate#26]
If a migration folder is empty, then this line with throw a runtime error: https://github.com/juanedi/micrate/blob/master/src/micrate.cr#L22

When `.last` is called on an empty collection, you get a runtime error:
https://carc.in/#/r/3f4d

**Comment by marksiemers** [comment]
Just checked to make sure, this is expected, documented behavior: https://crystal-lang.org/api/0.24.1/Indexable.html#last-instance-method

**Comment by faustinoaq** [comment]
@marksiemers I think we should check [this](https://github.com/veelenga/awesome-crystal/pull/241#issuecomment-353598767) 😅

**Comment by drujensen** [comment]
This is fixed in v0.9.0
