### ISSUE TITLE
Can't run micrate on Crystal 0.24.2

### ISSUE THREAD

**Issue by azah** [amberframework/micrate#29]
```
in lib/db/src/db/query_methods.cr:215: can't infer block return type, try to cast the block body with `as`. See: https://github.com/crystal-lang/crystal/wiki/Compiler-error-messages#cant-infer-block-return-type

      query_all(query, *args) do |rs|
      ^~~~~~~~~
```

crystal version:
```
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu
```

**Comment by epergo** [comment]
Hello @azah, I ran into this very issue today.

After a couple of tries I finally made it ran, first check that you have set the environment variable DB_URL as specified in Readme and second, if you have created an executable file to run micrate, remember to require your database adapter, in my case was postgres.

My `bin/micrate` file, for whats is worth:

```crystal
#! /usr/bin/env crystal
require "pg"
require "micrate"

Micrate::Cli.run
```

Then I was able to run `bin/micrate up` as usual. Hope it helps :smile:

**Comment by azah** [comment]
I forgot to add "pg" in my micrate. Thanks!
