### ISSUE TITLE
Curious about the state of this project

### ISSUE THREAD

**Issue by djmaze** [amberframework/micrate#38]
At the top of the README, it says:

> The Amber Team is currently working addressing Pending Issues, we will be notifying when a PR is ready for Community review.

The message is 9 months old already. 

Does it mean the project has serious issues and shouldn't currently be used?

**Comment by faustinoaq** [comment]
> Does it mean the project has serious issues and shouldn't currently be used?

I still think this is actively used by `amber db migrate`

The Amber team, @amberframework/contributors and community have been trying to organize these projects to become more stable.

We are open to new collaborators and developers :smile: 

Also other people on crystal community have created alternatives like https://github.com/vladfaust/migrate.cr by  @vladfaust

**Comment by faustinoaq** [comment]
I just updated README.md, I'm trying to review current status, Thank you for opening this issue :+1:

**Comment by djmaze** [comment]
@faustinoaq Thank you for the effort. I know how hard it is to maintain open source projects (particularly if that means sacrificing spare time). Kudos to you and the Amber team for the good work!

My intention was just to point out that the sentence might be misconceived as an advisory against using the project in its current state. 

That said, I just embedded this in a project of mine, and it seems to work just fine! Will see if I have anything to contribute later on.

**Comment by eliasjpr** [comment]
Actively used by the AmberFramework and we are picking up on contributions. Help wanted!
