### ISSUE TITLE
Version requirement breaking Amber

### ISSUE THREAD

**Issue by dburnsii** [amberframework/micrate#44]
The release of version v0.3.5 includes a requirement for a recent release of crystal-lang/crystal-db ~> v0.7.0. The dependencies for the currently released version of Amber (v0.30.1) and previous releases point to ~> v0.6.0. This is causing `shards install` to fail, and any project without a shard.lock file pointing to the correct versions fails to build.

A fix for this is to re-release this shard as version v0.3.x, with the version selection of crystal-db removed. Including the version is a good idea though, and it should be released with version v0.4.x to include the change without breaking existing projects.

Discussed with @elorest and he confirmed this as a solution.

**Comment by elorest** [comment]
Previous to 0.3.5 micrate pointed to `crystal-db` without a version. When crystal-db was just updated micrate automatically points to the newest version, while all other shards which depended on `crystal-db` correctly pointed to 0.6.0. This broke all past and present versions of amber. I'm going to fix this now by:

1. Releasing 0.3.5 to point to 0.6.0 of crystal-db.
2. Releasing 0.4.0 to point to 0.7.0 of crystal-db.

**Comment by drujensen** [comment]
Sorry. Should have bumped minor for this. - dru

**Comment by elorest** [comment]
That's fine. Thanks for working on it.
