### ISSUE TITLE
Incorrect shard reference in README

### ISSUE THREAD

**Issue by imdrasil** [amberframework/micrate#54]
[README](https://github.com/amberframework/micrate#api) file has incorrect reference for the shard - I guess it should be `amberframework/micrate` instead of `juanedi/micrate`

**Comment by captis-app** [comment]
Nope, just checked, and on Homebrew, it's still at `juanedi/micrate`, there's nothing at `amberframework/micrate`.

Whether that itself is an issue is a different question.

**Comment by imdrasil** [comment]
I installed it by adding to the `shard.yml` `github: amberframework/micrate`. Feel free to close this if everything is as expected

**Comment by Serdnad** [comment]
You're right, the shard was pointing to the wrong repo - it's been updated, although that repo currently redirects here anyway. The CLI binary, however, is still on homebrew under `juanedi/micrate`.

**Comment by drujensen** [comment]
This is fixed in v0.9.0
