### ISSUE TITLE
Failure To Build Amber from AUR

### ISSUE THREAD

**Issue by MaterialFuture** [amberframework/micrate#55]
I'm trying to get Amber working on my Arch machine but I'm getting the error for Micrate.
This may be an issue with the Amber Makefile.

```shell
Installing optarg (0.7.0)
Installing string_inflection (0.2.1)
Installing db (0.8.0)
Building amber in /home/materialfuture/.cache/yay/amber/src
Showing last frame. Use --error-trace for full trace.

In lib/micrate/src/micrate/db/sqlite3.cr:22:136

 22 | db.exec("INSERT INTO micrate_db_version (version_i

Error: undefined method 'now' for Time.class

Did you mean 'new'?
make: *** [Makefile:18: /home/materialfuture/.cache/yay/amb
==> ERROR: A failure occurred in build().
    Aborting...
Error making: amber
```
I'll try and debug further by trying to build manually from the snapshot to see what the issue could be, but posting for visibility in case others are having the same issue.

EDIT: Making directly from cloning the project works, not sure if the AUR is just outdated.
[Link to AUR](https://aur.archlinux.org/packages/amber/)

**Comment by MaterialFuture** [comment]
The AUR version is out of date so it's causing a conflict with with Amber v0.32.0.
I'm closing this since it really isn't related to Micrate, just AUR being out of date.

**Comment by faustinoaq** [comment]
Hi, @MaterialFuture I apologize for the late update. I forgot to update the latest version, I already developed a script to automate it and avoid a version delay.

Stay safe, Cheers.
