### ISSUE TITLE
No error message when password is incorrect

### ISSUE THREAD

**Issue by martimatix** [amberframework/micrate#60]
When the password to the database is incorrect in the connection url, no error message is produced. A blank line is output. Would be nice to see some sort of error message.

Using:
* micrate 0.8.0
* crystal 0.35.0
* postgres 12.1

**Comment by drujensen** [comment]
This is more than likely related to the `Logger` being replaced with `Log`. I don't think this was implemented correctly. This should be removed:
```
@@logger : Log?
```

And instead `Log.info { ... }` should be used.  That way, the end user can define how logging should be configured.

https://crystal-lang.org/api/0.35.0/Log.html

**Comment by drujensen** [comment]
This is fixed in v0.9.0
