### ISSUE TITLE
Instructions on how to use releases

### ISSUE THREAD

**Issue by emhohensee** [amberframework/micrate#63]
I'm totally new to crystal and I'm having trouble using this package. I tried downloading the source code release, running `shards install`, and then running `crystal build src/micrate.cr --release` in the directory. This builds an executable `micrate` file but when I try to use it, it does nothing and prints no help or error message.

I can see in the source code that it's supposed to print the help text if there are no arguments, but it's not even doing that.

**Comment by Serdnad** [comment]
@emhohensee To build an executable that can be run from a command line, compile this file https://github.com/amberframework/micrate/blob/master/examples/micrate.

Building `src/micrate` just builds the library.

**Comment by drujensen** [comment]
This is fixed in v0.9.0
