### ISSUE TITLE
Part about "micrate create" in README is incorrect

### ISSUE THREAD

**Issue by LVMBDV** [amberframework/micrate#70]
> To create a new migration use the create subcommand. For example, micrate create add_users_table will create a new SQL migration file with a name such as...

`micrate create` only creates a database as specified in the database url. See here:

https://github.com/amberframework/micrate/blob/master/src/micrate/cli.cr#L134

**Comment by drujensen** [comment]
Thanks for reporting this.  Can you create a PR?

**Comment by LVMBDV** [comment]
But do we want to just fix the README to omit migration creation or have `create` create migrations as expected and move the database creation to another command like `createdb`?

**Comment by drujensen** [comment]
It was renamed to "scaffold".  https://github.com/amberframework/micrate/blob/master/src/micrate/cli.cr#L121

**Comment by LVMBDV** [comment]
Oh so that's what that does, my bad. I'll fix the README.
