### ISSUE TITLE
Linux support.

### ISSUE THREAD

**Issue by chyzwar** [amberframework/micrate#8]
I pulled micrate as dependency and then build executable, Later I moved executable to root of my project. 
When I try to run any of the micrate commands I get silent failures. 

Looks like its runs executable but I do not get any results or error messages. 

Crystal 0.20.3
Ubuntu 16.04

**Comment by juanedi** [comment]
Hi @Chyzwar!

I just tried to reproduce it but everything seems to be working.

This is the minimal example I tried https://gist.github.com/juanedi/8293717c715cd1c144610b63c862b7d8.

I ran it on a fresh Vagrant box with Ubuntu 16.04 and Crystal 0.20.3. Does your example fail before or after `Micrate::Cli.run`? Which DB driver are you using?

**Comment by Chyzwar** [comment]
I tried to build micrate and use it as cli tool in the same way as goose. I was thinking that I can use it without runner script: 
```sh
micrate postgres "user=<user> dbname=tribe_users sslmode=disable" up 
```
I can see now that runner script is better idea :) I will try today and let you know.

**Comment by juanedi** [comment]
You can do both!

When you get the runner script working, you can do `crystal build micrate-runner.cr -o micrate` which will generate a compiled binary you can add to your PATH.

Take a look at https://github.com/juanedi/homebrew-micrate. That's the repo I use to build the precompiled OSX binary. It's basically the same runner script that includes all known drivers.

By default that binary will use the connection URL specified by the `DB_URL` environment variable.

**Comment by Chyzwar** [comment]
I made runner script and It work fine for create table:
![image](https://cloud.githubusercontent.com/assets/5990767/21974831/09273bd2-dbc1-11e6-8da2-34037d1eedf6.png)

But it would still fail for 'up'. I have two other migrations with SQL tested in DataGrip. DataGrip use the same username and password.

I am going to add some puts in micrate :P

**Comment by faustinoaq** [comment]
Hi @chyzwar Is this still an issue?

Now `micrate` is part of `amberframework` :tada:

**Comment by faustinoaq** [comment]
@amberframework/core-team Is this still an issue?
