### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SamantazFox** [amberframework/micrate#81]
What license is micrate released under? I can't find anything in this repo.
Is it MIT, like [amber](https://github.com/amberframework/amber)?

**Comment by drujensen-happymoney** [comment]
Good question.  @juanedi Can you provide guidance?  You are the creator of the project.

**Comment by drujensen** [comment]
I've added the MIT license:  https://github.com/amberframework/micrate/blob/master/LICENSE
